# Generated by Django 6.0.4 on 2026-05-05 00:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='jobs/banners/'),
        ),
    ]
