# Generated by Django 6.0.4 on 2026-05-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='companies/banners/'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/logos/'),
        ),
    ]
