# Generated by Django 6.0.4 on 2026-05-05 00:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_banner_image_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='companies/banners/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='companies/logos/'),
        ),
    ]
